---
openapi: 3.0.3
info:
  title: app
  version: 1.0.0
paths:
  "/api/ping":
    get:
      summary: ping
      tags:
      - Api
      responses:
        '200':
          description: v1 ping
          content:
            application/json:
              schema:
                type: string
              example: ok
